name: Build Geode Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up CMake
        uses: lukka/get-cmake@v3.26.4

      - name: Install Geode CLI
        run: |
          curl -L https://github.com/geode-sdk/geode/releases/download/v4.6.1/geode.exe -o geode.exe
          ./geode.exe init
      - name: Build Mod
        run: |
          ./geode.exe build
      - name: Upload .geode File
        uses: actions/upload-artifact@v4
        with:
          name: CrystalMenu
          path: build/*.geode
