name: Build Geode Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up CMake
        uses: lukka/get-cmake@v3.26.4

      - name: Install Geode SDK
        run: |
          Invoke-WebRequest -Uri https://github.com/geode-sdk/geode/releases/latest/download/geode.exe -OutFile geode.exe
          ./geode.exe init
        shell: pwsh

      - name: Build Mod
        run: |
          ./geode.exe build
        shell: pwsh

      - name: Upload .geode File
        uses: actions/upload-artifact@v4
        with:
          name: CrystalMenu
          path: build/*.geode
